steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'australia-southeast1-docker.pkg.dev/concrete-setup-429807-v6/ito4002/sveltejs-app:latest', '/client']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/concrete-setup-429807-v6/ito4002/sveltejs-app:latest']

images:
  - 'australia-southeast1-docker.pkg.dev/concrete-setup-429807-v6/ito4002/sveltejs-app'
