steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-project/ito5002/sveltejs-app:$COMMIT_SHA', './client']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-project/ito5002/sveltejs-app:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/my-project/ito5002/sveltejs-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY