export const dummyListingCards = [
    {
        id: 1,
        displayName: "Jamie Smith",
        rating: 4.5,
        suburb: "Marrickville",
        mode: 4,
        type: "Type 1",
        pricePerHour: 20,
        sustainable: true,
    },
    {
        id: 2,
        displayName: "Emma Johnson",
        rating: 4.2,
        suburb: "Surry Hills",
        mode: 3,
        type: "CHaDeMO",
        pricePerHour: 25,
        sustainable: true,
    },
    {
        id: 3,
        displayName: "Oliver Wilson",
        rating: 4.8,
        suburb: "Newtown",
        mode: 2,
        type: "Mennekes",
        pricePerHour: 18,
        sustainable: true,
    },
    {
        id: 4,
        displayName: "Sophia Brown",
        rating: 2.9,
        suburb: "Bondi",
        mode: 1,
        type: "Type 1",
        pricePerHour: 30,
        sustainable: false,
    },
    {
        id: 5,
        displayName: "Noah Taylor",
        rating: 4.3,
        suburb: "Manly",
        mode: 4,
        type: "Tesla",
        pricePerHour: 22,
        sustainable: true,
    },
    {
        id: 6,
        displayName: "Ava Davis",
        rating: 4.7,
        suburb: "Coogee",
        mode: 3,
        type: "Mennekes",
        pricePerHour: 19,
        sustainable: false,
    },
    {
        id: 7,
        displayName: "William Martinez",
        rating: 4.4,
        suburb: "Randwick",
        mode: 2,
        type: "Type 1",
        pricePerHour: 28,
        sustainable: true,
    },
    {
        id: 8,
        displayName: "Isabella Anderson",
        rating: 4.9,
        suburb: "Paddington",
        mode: 1,
        type: "CHaDeMO",
        pricePerHour: 24,
        sustainable: false,
    },
    {
        id: 9,
        displayName: "Mia Thomas",
        rating: 4.1,
        suburb: "Darlinghurst",
        mode: 4,
        type: "Tesla",
        pricePerHour: 21,
        sustainable: true,
    },
    {
        id: 10,
        displayName: "James Wilson",
        rating: 4.7,
        suburb: "Glebe",
        mode: 3,
        type: "Mennekes",
        pricePerHour: 23,
        sustainable: false,
    }
];
